//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseWebService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="WarehouseWebService", ConfigurationName="WarehouseWebService.WarehouseWebServiceSoap")]
    public interface WarehouseWebServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="WarehouseWebService/SendZamowienie", ReplyAction="*")]
        System.Threading.Tasks.Task<WarehouseWebService.SendZamowienieResponse> SendZamowienieAsync(WarehouseWebService.SendZamowienieRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="WarehouseWebService/GetTowary", ReplyAction="*")]
        System.Threading.Tasks.Task<WarehouseWebService.GetTowaryResponse> GetTowaryAsync(WarehouseWebService.GetTowaryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendZamowienieRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendZamowienie", Namespace="WarehouseWebService", Order=0)]
        public WarehouseWebService.SendZamowienieRequestBody Body;
        
        public SendZamowienieRequest()
        {
        }
        
        public SendZamowienieRequest(WarehouseWebService.SendZamowienieRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WarehouseWebService")]
    public partial class SendZamowienieRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int ilosc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string imie;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string nazwisko;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string adres;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string dostawa;
        
        public SendZamowienieRequestBody()
        {
        }
        
        public SendZamowienieRequestBody(int id, int ilosc, string imie, string nazwisko, string adres, string dostawa)
        {
            this.id = id;
            this.ilosc = ilosc;
            this.imie = imie;
            this.nazwisko = nazwisko;
            this.adres = adres;
            this.dostawa = dostawa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendZamowienieResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendZamowienieResponse", Namespace="WarehouseWebService", Order=0)]
        public WarehouseWebService.SendZamowienieResponseBody Body;
        
        public SendZamowienieResponse()
        {
        }
        
        public SendZamowienieResponse(WarehouseWebService.SendZamowienieResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SendZamowienieResponseBody
    {
        
        public SendZamowienieResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTowaryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTowary", Namespace="WarehouseWebService", Order=0)]
        public WarehouseWebService.GetTowaryRequestBody Body;
        
        public GetTowaryRequest()
        {
        }
        
        public GetTowaryRequest(WarehouseWebService.GetTowaryRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetTowaryRequestBody
    {
        
        public GetTowaryRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTowaryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTowaryResponse", Namespace="WarehouseWebService", Order=0)]
        public WarehouseWebService.GetTowaryResponseBody Body;
        
        public GetTowaryResponse()
        {
        }
        
        public GetTowaryResponse(WarehouseWebService.GetTowaryResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WarehouseWebService")]
    public partial class GetTowaryResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTowaryResult;
        
        public GetTowaryResponseBody()
        {
        }
        
        public GetTowaryResponseBody(string GetTowaryResult)
        {
            this.GetTowaryResult = GetTowaryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface WarehouseWebServiceSoapChannel : WarehouseWebService.WarehouseWebServiceSoap, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class WarehouseWebServiceSoapClient : System.ServiceModel.ClientBase<WarehouseWebService.WarehouseWebServiceSoap>, WarehouseWebService.WarehouseWebServiceSoap
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        public WarehouseWebServiceSoapClient() { 
}
        public WarehouseWebServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WarehouseWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), WarehouseWebServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WarehouseWebServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WarehouseWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WarehouseWebServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WarehouseWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WarehouseWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WarehouseWebService.SendZamowienieResponse> WarehouseWebService.WarehouseWebServiceSoap.SendZamowienieAsync(WarehouseWebService.SendZamowienieRequest request)
        {
            return base.Channel.SendZamowienieAsync(request);
        }
        
        public System.Threading.Tasks.Task<WarehouseWebService.SendZamowienieResponse> SendZamowienieAsync(int id, int ilosc, string imie, string nazwisko, string adres, string dostawa)
        {
            WarehouseWebService.SendZamowienieRequest inValue = new WarehouseWebService.SendZamowienieRequest();
            inValue.Body = new WarehouseWebService.SendZamowienieRequestBody();
            inValue.Body.id = id;
            inValue.Body.ilosc = ilosc;
            inValue.Body.imie = imie;
            inValue.Body.nazwisko = nazwisko;
            inValue.Body.adres = adres;
            inValue.Body.dostawa = dostawa;
            return ((WarehouseWebService.WarehouseWebServiceSoap)(this)).SendZamowienieAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WarehouseWebService.GetTowaryResponse> WarehouseWebService.WarehouseWebServiceSoap.GetTowaryAsync(WarehouseWebService.GetTowaryRequest request)
        {
            return base.Channel.GetTowaryAsync(request);
        }
        
        public System.Threading.Tasks.Task<WarehouseWebService.GetTowaryResponse> GetTowaryAsync()
        {
            WarehouseWebService.GetTowaryRequest inValue = new WarehouseWebService.GetTowaryRequest();
            inValue.Body = new WarehouseWebService.GetTowaryRequestBody();
            return ((WarehouseWebService.WarehouseWebServiceSoap)(this)).GetTowaryAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WarehouseWebServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WarehouseWebServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WarehouseWebServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44334/WarehouseWebService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WarehouseWebServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44334/WarehouseWebService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WarehouseWebServiceSoap,
            
            WarehouseWebServiceSoap12,
        }
    }
}
