//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseService
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "WarehouseWebService", ConfigurationName = "WarehouseWebServiceSoap")]
    public interface WarehouseWebServiceSoap
    {

        // CODEGEN: Generating message contract since element name imie from namespace WarehouseWebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "WarehouseWebService/SendZamowienie", ReplyAction = "*")]
        SendZamowienieResponse SendZamowienie(SendZamowienieRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "WarehouseWebService/SendZamowienie", ReplyAction = "*")]
        System.Threading.Tasks.Task<SendZamowienieResponse> SendZamowienieAsync(SendZamowienieRequest request);

        // CODEGEN: Generating message contract since element name GetTowaryResult from namespace WarehouseWebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "WarehouseWebService/GetTowary", ReplyAction = "*")]
        GetTowaryResponse GetTowary(GetTowaryRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "WarehouseWebService/GetTowary", ReplyAction = "*")]
        System.Threading.Tasks.Task<GetTowaryResponse> GetTowaryAsync(GetTowaryRequest request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class SendZamowienieRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "SendZamowienie", Namespace = "WarehouseWebService", Order = 0)]
        public SendZamowienieRequestBody Body;

        public SendZamowienieRequest()
        {
        }

        public SendZamowienieRequest(SendZamowienieRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "WarehouseWebService")]
    public partial class SendZamowienieRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(Order = 0)]
        public int id;

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public int ilosc;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string imie;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string nazwisko;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
        public string adres;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 5)]
        public string dostawa;

        public SendZamowienieRequestBody()
        {
        }

        public SendZamowienieRequestBody(int id, int ilosc, string imie, string nazwisko, string adres, string dostawa)
        {
            this.id = id;
            this.ilosc = ilosc;
            this.imie = imie;
            this.nazwisko = nazwisko;
            this.adres = adres;
            this.dostawa = dostawa;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class SendZamowienieResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "SendZamowienieResponse", Namespace = "WarehouseWebService", Order = 0)]
        public SendZamowienieResponseBody Body;

        public SendZamowienieResponse()
        {
        }

        public SendZamowienieResponse(SendZamowienieResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "WarehouseWebService")]
    public partial class SendZamowienieResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(Order = 0)]
        public bool SendZamowienieResult;

        public SendZamowienieResponseBody()
        {
        }

        public SendZamowienieResponseBody(bool SendZamowienieResult)
        {
            this.SendZamowienieResult = SendZamowienieResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetTowaryRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetTowary", Namespace = "WarehouseWebService", Order = 0)]
        public GetTowaryRequestBody Body;

        public GetTowaryRequest()
        {
        }

        public GetTowaryRequest(GetTowaryRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetTowaryRequestBody
    {

        public GetTowaryRequestBody()
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetTowaryResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetTowaryResponse", Namespace = "WarehouseWebService", Order = 0)]
        public GetTowaryResponseBody Body;

        public GetTowaryResponse()
        {
        }

        public GetTowaryResponse(GetTowaryResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "WarehouseWebService")]
    public partial class GetTowaryResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string GetTowaryResult;

        public GetTowaryResponseBody()
        {
        }

        public GetTowaryResponseBody(string GetTowaryResult)
        {
            this.GetTowaryResult = GetTowaryResult;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WarehouseWebServiceSoapChannel : WarehouseWebServiceSoap, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WarehouseWebServiceSoapClient : System.ServiceModel.ClientBase<WarehouseWebServiceSoap>, WarehouseWebServiceSoap
    {

        public WarehouseWebServiceSoapClient()
        {
        }

        public WarehouseWebServiceSoapClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public WarehouseWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public WarehouseWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public WarehouseWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SendZamowienieResponse WarehouseWebServiceSoap.SendZamowienie(SendZamowienieRequest request)
        {
            return base.Channel.SendZamowienie(request);
        }

        public bool SendZamowienie(int id, int ilosc, string imie, string nazwisko, string adres, string dostawa)
        {
            SendZamowienieRequest inValue = new SendZamowienieRequest();
            inValue.Body = new SendZamowienieRequestBody();
            inValue.Body.id = id;
            inValue.Body.ilosc = ilosc;
            inValue.Body.imie = imie;
            inValue.Body.nazwisko = nazwisko;
            inValue.Body.adres = adres;
            inValue.Body.dostawa = dostawa;
            SendZamowienieResponse retVal = ((WarehouseWebServiceSoap)(this)).SendZamowienie(inValue);
            return retVal.Body.SendZamowienieResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendZamowienieResponse> WarehouseWebServiceSoap.SendZamowienieAsync(SendZamowienieRequest request)
        {
            return base.Channel.SendZamowienieAsync(request);
        }

        public System.Threading.Tasks.Task<SendZamowienieResponse> SendZamowienieAsync(int id, int ilosc, string imie, string nazwisko, string adres, string dostawa)
        {
            SendZamowienieRequest inValue = new SendZamowienieRequest();
            inValue.Body = new SendZamowienieRequestBody();
            inValue.Body.id = id;
            inValue.Body.ilosc = ilosc;
            inValue.Body.imie = imie;
            inValue.Body.nazwisko = nazwisko;
            inValue.Body.adres = adres;
            inValue.Body.dostawa = dostawa;
            return ((WarehouseWebServiceSoap)(this)).SendZamowienieAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetTowaryResponse WarehouseWebServiceSoap.GetTowary(GetTowaryRequest request)
        {
            return base.Channel.GetTowary(request);
        }

        public string GetTowary()
        {
            GetTowaryRequest inValue = new GetTowaryRequest();
            inValue.Body = new GetTowaryRequestBody();
            GetTowaryResponse retVal = ((WarehouseWebServiceSoap)(this)).GetTowary(inValue);
            return retVal.Body.GetTowaryResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetTowaryResponse> WarehouseWebServiceSoap.GetTowaryAsync(GetTowaryRequest request)
        {
            return base.Channel.GetTowaryAsync(request);
        }

        public System.Threading.Tasks.Task<GetTowaryResponse> GetTowaryAsync()
        {
            GetTowaryRequest inValue = new GetTowaryRequest();
            inValue.Body = new GetTowaryRequestBody();
            return ((WarehouseWebServiceSoap)(this)).GetTowaryAsync(inValue);
        }
    }
}